baseURL = "http://masterbaiters.fish/"

languageCode = "en-us"
title = "Master Baiters"
theme = "blowfish"

[deployment]

[[deployment.targets]]
name = "production"
URL = "s3://masterbaiters.fish?region=us-east-1"