name: Hugo S3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  HUGO_VERSION: 0.128.2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out main
        uses: actions/checkout@master

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@3.0.0
        with:
          hugo-version: ${{ HUGO_VERSION }}
