name: Hugo S3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out main
        uses: actions/checkout@main

      - name: Build Site
        uses: chabad360/hugo-actions@master