name: Hugo S3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      hugoVersion: 'extended_0.128.0'

    steps:
      - name: Check out main
        uses: actions/checkout@master

      - name: Build Site
        uses: chabad360/hugo-actions@master